In [29]:
import torch

x = torch.arange(12)
x = x.reshape((3,4))
y = torch.arange(12)
y = y.reshape((3,4))
x,y

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

## 关于dim

In [30]:
# 0表示第一个维度 即行
torch.cat((x,y), dim=0)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [31]:
# 1代表第二个维度 即列
torch.cat((x,y), dim=1)

tensor([[ 0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7],
        [ 8,  9, 10, 11,  8,  9, 10, 11]])

## 关于内存分配问题

In [34]:
a = torch.arange(8).reshape((2,4))
b = torch.arange(8).reshape((2,4))
a ,b

(tensor([[0, 1, 2, 3],
         [4, 5, 6, 7]]),
 tensor([[0, 1, 2, 3],
         [4, 5, 6, 7]]))

In [40]:
before = id(a)
a += b
id(a), before

(2459808070104, 2459808070104)

In [41]:
a = a + b
id(a), before

(2459815216472, 2459808070104)