In [4]:
import torch

# 求和

In [6]:
x = torch.arange(12).reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
x.sum()

tensor(66)

In [8]:
x.sum(axis=0)

tensor([12, 15, 18, 21])

In [14]:
x.sum(axis=1)

tensor([ 6, 22, 38])

keepdims 可以保持维度不会减少 这样就可以继续使用广播机制
例如求出每行的每个数据在本行所占比例大小

In [10]:
x.sum(axis=0, keepdims=True)

tensor([[12, 15, 18, 21]])

In [11]:
x.sum(axis=1, keepdims=True)

tensor([[ 6],
        [22],
        [38]])

# 乘法

In [27]:
a = torch.arange(12).reshape(3,4)
b = torch.arange(12).reshape(4,3)
c = torch.arange(4).reshape(4)
a,b,c

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]),
 tensor([0, 1, 2, 3]))

In [31]:
torch.mv(a,c)

tensor([14, 38, 62])

In [34]:
torch.mm(a, b)

tensor([[ 42,  48,  54],
        [114, 136, 158],
        [186, 224, 262]])

L1范数 向量各个元素绝对值之和<br>
L2范数 向量各个元素平方和再开方

In [37]:
a = torch.ones((2,1), dtype=float)
torch.norm(a)

tensor(1.4142, dtype=torch.float64)