In [1]:
import torch

In [3]:
x = torch.arange(4.0)

# 保存x的梯度在x.grad
x.requires_grad_(True)

y = 2*torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [4]:
y.backward()
x.grad 

tensor([ 0.,  4.,  8., 12.])

In [10]:
# 默认情况下，会累计梯度，我们需要清除之前的值
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [11]:
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])